
package telainicial;

import telainicial.model.Cliente; // Importa o modelo Cliente
import java.sql.SQLException; // Para tratar erros de BD
import java.util.List; // Para usar listas
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // Para manipular a JTable
import telainicial.model.ClienteDAO;

public class ListarClientes extends javax.swing.JFrame {

    private final ClienteDAO clienteDAO = new ClienteDAO();
    
    private void excluirClienteSelecionado() {
    int linhaSelecionada = jtableClientes.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jtableClientes.getModel();
    
    // **ASSUNÇÃO CRÍTICA**: O CPF está na primeira coluna (índice 0)
    String cpfCliente = (String) model.getValueAt(linhaSelecionada, 0); 

    int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir o cliente com CPF: " + cpfCliente + "?", 
            "Confirmação de Exclusão", 
            JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            clienteDAO.excluir(cpfCliente);
            JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            // Recarrega a lista para remover a linha excluída da JTable
            carregarDadosClientes();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao excluir cliente: " + ex.getMessage(), 
                    "Erro de Exclusão", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
}
    /**
     * Creates new form ListarClientes
     */
    public ListarClientes() {
        initComponents();
        // CORREÇÃO CRÍTICA: Define para fechar apenas esta janela, não o programa inteiro.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        
        // 2. Carrega os dados do banco e preenche a tabela ao abrir a tela
        carregarDadosClientes();
    }

    // -----------------------------------------------------------
    // MÉTODO: Busca dados no DAO e preenche a JTable
    // -----------------------------------------------------------
    private void carregarDadosClientes() {
        // Obtém o modelo da sua JTable (jtableClientes)
        DefaultTableModel model = (DefaultTableModel) jtableClientes.getModel();
        model.setRowCount(0); // Limpa as linhas existentes para um novo carregamento

        try {
            // 1. Busca a lista de clientes usando o ClienteDAO
            List<Cliente> clientes = clienteDAO.listarTodos();

            if (clientes.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado no banco de dados.", 
                                              "Aviso", JOptionPane.INFORMATION_MESSAGE);
                 return; 
            }

            // 2. Adiciona cada cliente como uma nova linha
            for (Cliente cliente : clientes) {
                model.addRow(new Object[]{
                    cliente.getCpf(),
                    cliente.getNome(),
                    cliente.getTelefone(),
                    cliente.getEmail()
                });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar dados do banco. Verifique a Conexão e o Driver JDBC: " + ex.getMessage(), 
                "Erro de BD", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableClientes = new javax.swing.JTable();
        bntVoltar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Clientes");

        jtableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Telefone", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(jtableClientes);

        bntVoltar.setText("Voltar");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntExcluir)
                .addGap(18, 18, 18)
                .addComponent(bntVoltar)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntVoltar)
                    .addComponent(bntExcluir))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        excluirClienteSelecionado();
    }//GEN-LAST:event_bntExcluirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableClientes;
    // End of variables declaration//GEN-END:variables
}
